// ── Realistic webhook test payloads for well-known providers ──
// Each payload includes the headers that our inferSource() recognizes
// plus a realistic body that mirrors what the actual provider sends.

export interface TestPayload {
  method: string;
  headers: Record<string, string>;
  body: any;
  source: string;
}

export interface ProviderEvents {
  name: string;
  events: Record<string, { label: string; payload: TestPayload }>;
}

export const testerProviders: Record<string, ProviderEvents> = {
  stripe: {
    name: 'Stripe',
    events: {
      'invoice.payment_succeeded': {
        label: 'Invoice Payment Succeeded',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'Stripe/1.0 (+https://stripe.com/docs/webhooks)',
            'content-type': 'application/json',
            'stripe-signature': 't=1234567890,v1=mock_signature',
          },
          source: 'stripe',
          body: {
            id: 'evt_' + randomId(24),
            object: 'event',
            api_version: '2024-04-10',
            created: Math.floor(Date.now() / 1000),
            type: 'invoice.payment_succeeded',
            data: {
              object: {
                id: 'in_' + randomId(24),
                object: 'invoice',
                amount_due: 1999,
                amount_paid: 1999,
                amount_remaining: 0,
                currency: 'usd',
                customer: 'cus_' + randomId(14),
                status: 'paid',
                subscription: 'sub_' + randomId(24),
                total: 1999,
                hosted_invoice_url: 'https://invoice.stripe.com/i/' + randomId(24),
                invoice_pdf: 'https://pay.stripe.com/invoice/' + randomId(24) + '/pdf',
              },
            },
            livemode: false,
            pending_webhooks: 1,
            request: { id: 'req_' + randomId(24), idempotency_key: randomId(32) },
          },
        },
      },
      'customer.created': {
        label: 'Customer Created',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'Stripe/1.0 (+https://stripe.com/docs/webhooks)',
            'content-type': 'application/json',
            'stripe-signature': 't=1234567890,v1=mock_signature',
          },
          source: 'stripe',
          body: {
            id: 'evt_' + randomId(24),
            object: 'event',
            api_version: '2024-04-10',
            created: Math.floor(Date.now() / 1000),
            type: 'customer.created',
            data: {
              object: {
                id: 'cus_' + randomId(14),
                object: 'customer',
                address: { city: 'San Francisco', country: 'US', line1: '123 Market St', postal_code: '94105', state: 'CA' },
                balance: 0,
                created: Math.floor(Date.now() / 1000),
                currency: 'usd',
                default_source: null,
                delinquent: false,
                description: 'Test Customer',
                discount: null,
                email: 'customer@example.com',
                invoice_prefix: randomId(8).toUpperCase(),
                livemode: false,
                metadata: {},
                name: 'Test Customer',
                phone: '+14155551234',
                preferred_locales: ['en'],
                shipping: null,
                tax_exempt: 'none',
              },
            },
            livemode: false,
            pending_webhooks: 1,
            request: { id: 'req_' + randomId(24), idempotency_key: randomId(32) },
          },
        },
      },
      'charge.succeeded': {
        label: 'Charge Succeeded',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'Stripe/1.0 (+https://stripe.com/docs/webhooks)',
            'content-type': 'application/json',
            'stripe-signature': 't=1234567890,v1=mock_signature',
          },
          source: 'stripe',
          body: {
            id: 'evt_' + randomId(24),
            object: 'event',
            api_version: '2024-04-10',
            created: Math.floor(Date.now() / 1000),
            type: 'charge.succeeded',
            data: {
              object: {
                id: 'ch_' + randomId(24),
                object: 'charge',
                amount: 1999,
                amount_captured: 1999,
                amount_refunded: 0,
                application: null,
                application_fee: null,
                balance_transaction: 'txn_' + randomId(24),
                billing_details: { address: { city: 'San Francisco', country: 'US', line1: '123 Market St', postal_code: '94105', state: 'CA' }, email: 'customer@example.com', name: 'Test Customer', phone: null },
                calculated_statement_descriptor: 'HOOKSWING',
                captured: true,
                created: Math.floor(Date.now() / 1000),
                currency: 'usd',
                customer: 'cus_' + randomId(14),
                description: 'Subscription update',
                disputed: false,
                failure_balance_transaction: null,
                failure_code: null,
                failure_message: null,
                invoice: 'in_' + randomId(24),
                livemode: false,
                metadata: {},
                paid: true,
                payment_intent: 'pi_' + randomId(24),
                payment_method: 'pm_' + randomId(24),
                receipt_email: 'customer@example.com',
                receipt_number: null,
                receipt_url: 'https://pay.stripe.com/receipts/' + randomId(24),
                refunded: false,
                shipping: null,
                status: 'succeeded',
              },
            },
            livemode: false,
            pending_webhooks: 1,
            request: { id: 'req_' + randomId(24), idempotency_key: randomId(32) },
          },
        },
      },
      'subscription.created': {
        label: 'Subscription Created',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'Stripe/1.0 (+https://stripe.com/docs/webhooks)',
            'content-type': 'application/json',
            'stripe-signature': 't=1234567890,v1=mock_signature',
          },
          source: 'stripe',
          body: {
            id: 'evt_' + randomId(24),
            object: 'event',
            api_version: '2024-04-10',
            created: Math.floor(Date.now() / 1000),
            type: 'subscription.created',
            data: {
              object: {
                id: 'sub_' + randomId(24),
                object: 'subscription',
                application_fee_percent: null,
                automatic_tax: { enabled: false, liability: null },
                billing_cycle_anchor: Math.floor(Date.now() / 1000),
                billing_thresholds: null,
                cancel_at: null,
                cancel_at_period_end: false,
                canceled_at: null,
                collection_method: 'charge_automatically',
                created: Math.floor(Date.now() / 1000),
                currency: 'usd',
                current_period_end: Math.floor(Date.now() / 1000) + 2592000,
                current_period_start: Math.floor(Date.now() / 1000),
                customer: 'cus_' + randomId(14),
                days_until_due: null,
                default_payment_method: null,
                default_tax_rates: [],
                description: null,
                discount: null,
                ended_at: null,
                items: {
                  object: 'list',
                  data: [{
                    id: 'si_' + randomId(24),
                    object: 'subscription_item',
                    billing_thresholds: null,
                    created: Math.floor(Date.now() / 1000),
                    plan: { id: 'price_' + randomId(24), object: 'plan', active: true, aggregate_usage: null, amount: 1999, amount_decimal: '1999', billing_scheme: 'per_unit', created: Math.floor(Date.now() / 1000), currency: 'usd', interval: 'month', interval_count: 1, livemode: false, metadata: {}, nickname: null, product: 'prod_' + randomId(24), tiers_mode: null, transform_usage: null, trial_period_days: null, usage_type: 'licensed' },
                    price: { id: 'price_' + randomId(24), object: 'price', active: true, billing_scheme: 'per_unit', created: Math.floor(Date.now() / 1000), currency: 'usd', custom_unit_amount: null, livemode: false, lookup_key: null, metadata: {}, nickname: null, product: 'prod_' + randomId(24), recurring: { aggregate_usage: null, interval: 'month', interval_count: 1, trial_period_days: null, usage_type: 'licensed' }, tax_behavior: 'unspecified', tiers_mode: null, transform_quantity: null, type: 'recurring', unit_amount: 1999, unit_amount_decimal: '1999' },
                    quantity: 1,
                    subscription: 'sub_' + randomId(24),
                    tax_rates: [],
                  }],
                  has_more: false,
                  total_count: 1,
                  url: '/v1/subscription_items?subscription=sub_' + randomId(24),
                },
                latest_invoice: 'in_' + randomId(24),
                livemode: false,
                metadata: {},
                next_pending_invoice_item_invoice: null,
                on_behalf_of: null,
                pause_collection: null,
                payment_settings: { payment_method_options: null, payment_method_types: null, save_default_payment_method: 'off' },
                pending_invoice_item_interval: null,
                pending_setup_intent: null,
                pending_update: null,
                plan: { id: 'price_' + randomId(24), object: 'plan', active: true, aggregate_usage: null, amount: 1999, amount_decimal: '1999', billing_scheme: 'per_unit', created: Math.floor(Date.now() / 1000), currency: 'usd', interval: 'month', interval_count: 1, livemode: false, metadata: {}, nickname: null, product: 'prod_' + randomId(24), tiers_mode: null, transform_usage: null, trial_period_days: null, usage_type: 'licensed' },
                quantity: 1,
                schedule: null,
                start_date: Math.floor(Date.now() / 1000),
                status: 'active',
                tax_percent: null,
                trial_end: null,
                trial_start: null,
              },
            },
            livemode: false,
            pending_webhooks: 1,
            request: { id: 'req_' + randomId(24), idempotency_key: randomId(32) },
          },
        },
      },
      'payment_intent.succeeded': {
        label: 'Payment Intent Succeeded',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'Stripe/1.0 (+https://stripe.com/docs/webhooks)',
            'content-type': 'application/json',
            'stripe-signature': 't=1234567890,v1=mock_signature',
          },
          source: 'stripe',
          body: {
            id: 'evt_' + randomId(24),
            object: 'event',
            api_version: '2024-04-10',
            created: Math.floor(Date.now() / 1000),
            type: 'payment_intent.succeeded',
            data: {
              object: {
                id: 'pi_' + randomId(24),
                object: 'payment_intent',
                amount: 1999,
                amount_capturable: 0,
                amount_details: { tip: {} },
                amount_received: 1999,
                application: null,
                application_fee_amount: null,
                automatic_payment_methods: { allow_redirects: 'always', enabled: true },
                canceled_at: null,
                cancellation_reason: null,
                capture_method: 'automatic',
                client_secret: 'pi_' + randomId(24) + '_secret_' + randomId(24),
                confirmation_method: 'automatic',
                created: Math.floor(Date.now() / 1000),
                currency: 'usd',
                customer: 'cus_' + randomId(14),
                description: 'Subscription update',
                invoice: 'in_' + randomId(24),
                last_payment_error: null,
                latest_charge: 'ch_' + randomId(24),
                livemode: false,
                metadata: {},
                next_action: null,
                on_behalf_of: null,
                payment_method: 'pm_' + randomId(24),
                payment_method_types: ['card'],
                processing: null,
                receipt_email: 'customer@example.com',
                review: null,
                setup_future_usage: null,
                shipping: null,
                source: null,
                status: 'succeeded',
              },
            },
            livemode: false,
            pending_webhooks: 1,
            request: { id: 'req_' + randomId(24), idempotency_key: randomId(32) },
          },
        },
      },
    },
  },

  github: {
    name: 'GitHub',
    events: {
      push: {
        label: 'Push',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'GitHub-Hookshot/12345678',
            'content-type': 'application/json',
            'x-github-event': 'push',
            'x-github-delivery': randomId(32),
            'x-hub-signature-256': 'sha256=mock_signature',
          },
          source: 'github',
          body: {
            ref: 'refs/heads/main',
            before: randomHex(40),
            after: randomHex(40),
            repository: {
              id: 123456789,
              node_id: 'R_' + randomId(10),
              name: 'hookswing',
              full_name: 'MBAS89/hookswing',
              private: false,
              owner: { login: 'MBAS89', id: 12345678, node_id: 'U_' + randomId(10), avatar_url: 'https://avatars.githubusercontent.com/u/12345678?v=4', gravatar_id: '', url: 'https://api.github.com/users/MBAS89', html_url: 'https://github.com/MBAS89', type: 'User', site_admin: false },
              html_url: 'https://github.com/MBAS89/hookswing',
              description: 'Webhook testing platform',
              fork: false,
              url: 'https://api.github.com/repos/MBAS89/hookswing',
              created_at: new Date().toISOString(),
              updated_at: new Date().toISOString(),
              pushed_at: new Date().toISOString(),
              git_url: 'git://github.com/MBAS89/hookswing.git',
              ssh_url: 'git@github.com:MBAS89/hookswing.git',
              clone_url: 'https://github.com/MBAS89/hookswing.git',
              size: 1234,
              stargazers_count: 42,
              watchers_count: 42,
              language: 'TypeScript',
              forks_count: 5,
              open_issues_count: 3,
              default_branch: 'main',
            },
            pusher: { name: 'MBAS89', email: 'dev@example.com' },
            sender: { login: 'MBAS89', id: 12345678, node_id: 'U_' + randomId(10), avatar_url: 'https://avatars.githubusercontent.com/u/12345678?v=4', html_url: 'https://github.com/MBAS89', type: 'User', site_admin: false },
            created: false,
            deleted: false,
            forced: false,
            base_ref: null,
            compare: 'https://github.com/MBAS89/hookswing/compare/' + randomHex(12) + '...' + randomHex(12),
            commits: [
              { id: randomHex(40), tree_id: randomHex(40), distinct: true, message: 'feat: add webhook tester tool\n\n- New tester page with provider selection\n- Realistic payloads for Stripe, GitHub, Shopify, etc.', timestamp: new Date().toISOString(), url: 'https://github.com/MBAS89/hookswing/commit/' + randomHex(40), author: { name: 'MBAS89', email: 'dev@example.com', username: 'MBAS89' }, committer: { name: 'MBAS89', email: 'dev@example.com', username: 'MBAS89' }, added: ['apps/web/src/pages/TesterPage.tsx'], removed: [], modified: [] },
            ],
            head_commit: { id: randomHex(40), tree_id: randomHex(40), distinct: true, message: 'feat: add webhook tester tool', timestamp: new Date().toISOString(), url: 'https://github.com/MBAS89/hookswing/commit/' + randomHex(40), author: { name: 'MBAS89', email: 'dev@example.com', username: 'MBAS89' }, committer: { name: 'MBAS89', email: 'dev@example.com', username: 'MBAS89' }, added: [], removed: [], modified: ['apps/web/src/pages/TesterPage.tsx'] },
          },
        },
      },
      'pull_request': {
        label: 'Pull Request',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'GitHub-Hookshot/12345678',
            'content-type': 'application/json',
            'x-github-event': 'pull_request',
            'x-github-delivery': randomId(32),
            'x-hub-signature-256': 'sha256=mock_signature',
          },
          source: 'github',
          body: {
            action: 'opened',
            number: 42,
            pull_request: {
              url: 'https://api.github.com/repos/MBAS89/hookswing/pulls/42',
              id: 1234567890,
              node_id: 'PR_' + randomId(10),
              html_url: 'https://github.com/MBAS89/hookswing/pull/42',
              diff_url: 'https://github.com/MBAS89/hookswing/pull/42.diff',
              patch_url: 'https://github.com/MBAS89/hookswing/pull/42.patch',
              issue_url: 'https://api.github.com/repos/MBAS89/hookswing/issues/42',
              number: 42,
              state: 'open',
              locked: false,
              title: 'feat: add webhook tester tool',
              user: { login: 'MBAS89', id: 12345678, node_id: 'U_' + randomId(10), avatar_url: 'https://avatars.githubusercontent.com/u/12345678?v=4', html_url: 'https://github.com/MBAS89', type: 'User', site_admin: false },
              body: 'This PR adds a new webhook tester tool to the dashboard.',
              created_at: new Date().toISOString(),
              updated_at: new Date().toISOString(),
              closed_at: null,
              merged_at: null,
              merge_commit_sha: null,
              assignee: null,
              assignees: [],
              requested_reviewers: [],
              labels: [{ id: 1234567890, node_id: 'LA_' + randomId(10), url: 'https://api.github.com/repos/MBAS89/hookswing/labels/enhancement', name: 'enhancement', color: 'a2eeef', default: true, description: 'New feature or request' }],
              head: { label: 'MBAS89:feat/tester', ref: 'feat/tester', sha: randomHex(40), user: { login: 'MBAS89', id: 12345678 }, repo: { id: 123456789, name: 'hookswing', full_name: 'MBAS89/hookswing' } },
              base: { label: 'MBAS89:main', ref: 'main', sha: randomHex(40), user: { login: 'MBAS89', id: 12345678 }, repo: { id: 123456789, name: 'hookswing', full_name: 'MBAS89/hookswing' } },
            },
            repository: { id: 123456789, name: 'hookswing', full_name: 'MBAS89/hookswing', private: false, owner: { login: 'MBAS89', id: 12345678 } },
            sender: { login: 'MBAS89', id: 12345678 },
          },
        },
      },
      issues: {
        label: 'Issues',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'GitHub-Hookshot/12345678',
            'content-type': 'application/json',
            'x-github-event': 'issues',
            'x-github-delivery': randomId(32),
            'x-hub-signature-256': 'sha256=mock_signature',
          },
          source: 'github',
          body: {
            action: 'opened',
            issue: {
              url: 'https://api.github.com/repos/MBAS89/hookswing/issues/42',
              repository_url: 'https://api.github.com/repos/MBAS89/hookswing',
              labels_url: 'https://api.github.com/repos/MBAS89/hookswing/issues/42/labels{/name}',
              comments_url: 'https://api.github.com/repos/MBAS89/hookswing/issues/42/comments',
              events_url: 'https://api.github.com/repos/MBAS89/hookswing/issues/42/events',
              html_url: 'https://github.com/MBAS89/hookswing/issues/42',
              id: 1234567890,
              node_id: 'I_' + randomId(10),
              number: 42,
              title: 'Feature request: webhook tester tool',
              user: { login: 'MBAS89', id: 12345678, node_id: 'U_' + randomId(10), avatar_url: 'https://avatars.githubusercontent.com/u/12345678?v=4', html_url: 'https://github.com/MBAS89', type: 'User', site_admin: false },
              labels: [],
              state: 'open',
              locked: false,
              assignee: null,
              assignees: [],
              milestone: null,
              comments: 0,
              created_at: new Date().toISOString(),
              updated_at: new Date().toISOString(),
              closed_at: null,
              body: 'It would be great to have a built-in webhook tester in the dashboard.',
            },
            repository: { id: 123456789, name: 'hookswing', full_name: 'MBAS89/hookswing', private: false, owner: { login: 'MBAS89', id: 12345678 } },
            sender: { login: 'MBAS89', id: 12345678 },
          },
        },
      },
      star: {
        label: 'Star',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'GitHub-Hookshot/12345678',
            'content-type': 'application/json',
            'x-github-event': 'star',
            'x-github-delivery': randomId(32),
            'x-hub-signature-256': 'sha256=mock_signature',
          },
          source: 'github',
          body: {
            action: 'created',
            starred_at: new Date().toISOString(),
            repository: { id: 123456789, name: 'hookswing', full_name: 'MBAS89/hookswing', private: false, owner: { login: 'MBAS89', id: 12345678 }, html_url: 'https://github.com/MBAS89/hookswing', stargazers_count: 43, watchers_count: 43 },
            sender: { login: 'contributor', id: 87654321, node_id: 'U_' + randomId(10), avatar_url: 'https://avatars.githubusercontent.com/u/87654321?v=4', html_url: 'https://github.com/contributor', type: 'User', site_admin: false },
          },
        },
      },
      release: {
        label: 'Release',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'GitHub-Hookshot/12345678',
            'content-type': 'application/json',
            'x-github-event': 'release',
            'x-github-delivery': randomId(32),
            'x-hub-signature-256': 'sha256=mock_signature',
          },
          source: 'github',
          body: {
            action: 'published',
            release: {
              url: 'https://api.github.com/repos/MBAS89/hookswing/releases/12345678',
              assets_url: 'https://api.github.com/repos/MBAS89/hookswing/releases/12345678/assets',
              upload_url: 'https://uploads.github.com/repos/MBAS89/hookswing/releases/12345678/assets{?name,label}',
              html_url: 'https://github.com/MBAS89/hookswing/releases/tag/v1.2.0',
              id: 12345678,
              node_id: 'RE_' + randomId(10),
              tag_name: 'v1.2.0',
              target_commitish: 'main',
              name: 'v1.2.0 - Webhook Tester',
              draft: false,
              author: { login: 'MBAS89', id: 12345678, node_id: 'U_' + randomId(10), avatar_url: 'https://avatars.githubusercontent.com/u/12345678?v=4', html_url: 'https://github.com/MBAS89', type: 'User', site_admin: false },
              prerelease: false,
              created_at: new Date().toISOString(),
              published_at: new Date().toISOString(),
              body: '## New Features\n- Webhook Tester tool\n- Support for 15+ providers\n- CLI source identification',
            },
            repository: { id: 123456789, name: 'hookswing', full_name: 'MBAS89/hookswing', private: false, owner: { login: 'MBAS89', id: 12345678 } },
            sender: { login: 'MBAS89', id: 12345678 },
          },
        },
      },
    },
  },

  paypal: {
    name: 'PayPal',
    events: {
      'PAYMENT.CAPTURE.COMPLETED': {
        label: 'Payment Capture Completed',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'PayPal/AQ1S4S4S4S4S4',
            'content-type': 'application/json',
            'paypal-auth-algo': 'SHA256withRSA',
            'paypal-cert-url': 'https://api.paypal.com/v1/notifications/certs/CERT-' + randomId(10),
            'paypal-transmission-id': randomId(32),
            'paypal-transmission-sig': 'mock_signature',
            'paypal-transmission-time': new Date().toISOString(),
          },
          source: 'paypal',
          body: {
            id: 'WH-' + randomId(17),
            event_version: '1.0',
            create_time: new Date().toISOString(),
            resource_type: 'capture',
            event_type: 'PAYMENT.CAPTURE.COMPLETED',
            summary: 'Payment completed for $ 19.99 USD',
            resource: {
              id: randomId(17),
              amount: { currency_code: 'USD', value: '19.99' },
              final_capture: true,
              seller_protection: { status: 'ELIGIBLE', dispute_categories: ['ITEM_NOT_RECEIVED', 'UNAUTHORIZED_TRANSACTION'] },
              status: 'COMPLETED',
              create_time: new Date().toISOString(),
              update_time: new Date().toISOString(),
              seller_receivable_breakdown: { gross_amount: { currency_code: 'USD', value: '19.99' }, paypal_fee: { currency_code: 'USD', value: '0.88' }, net_amount: { currency_code: 'USD', value: '19.11' } },
              links: [{ href: 'https://api.paypal.com/v2/payments/captures/' + randomId(17), rel: 'self', method: 'GET' }],
            },
            links: [{ href: 'https://api.paypal.com/v1/notifications/webhooks-events/' + randomId(17), rel: 'self', method: 'GET' }],
          },
        },
      },
      'BILLING.SUBSCRIPTION.CREATED': {
        label: 'Subscription Created',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'PayPal/AQ1S4S4S4S4S4',
            'content-type': 'application/json',
            'paypal-auth-algo': 'SHA256withRSA',
            'paypal-cert-url': 'https://api.paypal.com/v1/notifications/certs/CERT-' + randomId(10),
            'paypal-transmission-id': randomId(32),
            'paypal-transmission-sig': 'mock_signature',
            'paypal-transmission-time': new Date().toISOString(),
          },
          source: 'paypal',
          body: {
            id: 'WH-' + randomId(17),
            event_version: '1.0',
            create_time: new Date().toISOString(),
            resource_type: 'subscription',
            event_type: 'BILLING.SUBSCRIPTION.CREATED',
            summary: 'Subscription created',
            resource: {
              id: 'I-' + randomId(12),
              plan_id: 'P-' + randomId(12),
              start_time: new Date().toISOString(),
              quantity: '1',
              shipping_amount: { currency_code: 'USD', value: '0.00' },
              subscriber: { name: { given_name: 'Test', surname: 'Customer' }, email_address: 'customer@example.com', payer_id: randomId(13), shipping_address: { name: { full_name: 'Test Customer' }, address: { address_line_1: '123 Market St', admin_area_2: 'San Francisco', admin_area_1: 'CA', postal_code: '94105', country_code: 'US' } } },
              billing_info: { outstanding_balance: { currency_code: 'USD', value: '0.00' }, cycle_executions: [{ tenure_type: 'REGULAR', sequence: 1, cycles_completed: 0, cycles_remaining: 0, current_pricing_scheme_version: 1 }], last_payment: { amount: { currency_code: 'USD', value: '19.99' }, time: new Date().toISOString() }, next_billing_time: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(), failed_payments_count: 0 },
              create_time: new Date().toISOString(),
              update_time: new Date().toISOString(),
              links: [{ href: 'https://api.paypal.com/v1/billing/subscriptions/I-' + randomId(12), rel: 'self', method: 'GET' }],
              status: 'APPROVED',
              status_update_time: new Date().toISOString(),
            },
            links: [{ href: 'https://api.paypal.com/v1/notifications/webhooks-events/' + randomId(17), rel: 'self', method: 'GET' }],
          },
        },
      },
    },
  },

  shopify: {
    name: 'Shopify',
    events: {
      'orders/create': {
        label: 'Order Created',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'Shopify-Captain-Hook',
            'content-type': 'application/json',
            'x-shopify-topic': 'orders/create',
            'x-shopify-shop-domain': 'hookswing-store.myshopify.com',
            'x-shopify-order-id': randomId(13),
            'x-shopify-webhook-id': randomId(32),
            'x-shopify-api-version': '2024-04',
          },
          source: 'shopify',
          body: {
            id: parseInt(randomId(13)),
            admin_graphql_api_id: 'gid://shopify/Order/' + randomId(13),
            app_id: 1234567,
            browser_ip: '192.168.1.1',
            buyer_accepts_marketing: false,
            cancel_reason: null,
            cancelled_at: null,
            cart_token: randomId(32),
            checkout_id: parseInt(randomId(13)),
            checkout_token: randomId(32),
            client_details: { browser_ip: '192.168.1.1', accept_language: 'en-US', user_agent: 'Mozilla/5.0', session_hash: null, browser_width: 1920, browser_height: 1080 },
            closed_at: null,
            confirmed: true,
            contact_email: 'customer@example.com',
            created_at: new Date().toISOString(),
            currency: 'USD',
            current_subtotal_price: '89.99',
            current_total_discounts: '0.00',
            current_total_duties_set: null,
            current_total_price: '89.99',
            current_total_tax: '0.00',
            customer_locale: 'en-US',
            device_id: null,
            discount_codes: [],
            email: 'customer@example.com',
            financial_status: 'paid',
            fulfillment_status: null,
            landing_site: '/',
            location_id: null,
            name: '#1001',
            note: null,
            note_attributes: [],
            number: 1,
            order_number: 1001,
            order_status_url: 'https://hookswing-store.myshopify.com/12345678/orders/' + randomHex(32) + '/authenticate',
            original_total_duties_set: null,
            payment_gateway_names: ['bogus'],
            phone: null,
            presentment_currency: 'USD',
            processed_at: new Date().toISOString(),
            processing_method: '',
            reference: null,
            referring_site: '',
            source_identifier: null,
            source_name: 'web',
            source_url: null,
            subtotal_price: '89.99',
            tags: '',
            tax_lines: [],
            taxes_included: false,
            test: true,
            token: randomHex(32),
            total_discounts: '0.00',
            total_line_items_price: '89.99',
            total_outstanding: '0.00',
            total_price: '89.99',
            total_price_usd: '89.99',
            total_shipping_price_set: { shop_money: { amount: '0.00', currency_code: 'USD' }, presentment_money: { amount: '0.00', currency_code: 'USD' } },
            total_tax: '0.00',
            total_tip_received: '0.00',
            total_weight: 0,
            updated_at: new Date().toISOString(),
            user_id: null,
            billing_address: { first_name: 'Test', last_name: 'Customer', company: null, address1: '123 Market St', address2: null, city: 'San Francisco', province: 'California', country: 'United States', zip: '94105', phone: '+14155551234', name: 'Test Customer', province_code: 'CA', country_code: 'US', country_name: 'United States', default: false },
            customer: { id: parseInt(randomId(13)), email: 'customer@example.com', accepts_marketing: false, created_at: new Date().toISOString(), updated_at: new Date().toISOString(), first_name: 'Test', last_name: 'Customer', orders_count: 1, state: 'disabled', total_spent: '89.99', last_order_id: parseInt(randomId(13)), note: null, verified_email: true, tax_exempt: false, tags: '', last_order_name: '#1001', currency: 'USD', phone: null, addresses: [], accepts_marketing_updated_at: new Date().toISOString(), marketing_opt_in_level: null, tax_exemptions: [], email_marketing_consent: { state: 'not_subscribed', opt_in_level: 'single_opt_in', consent_updated_at: null }, sms_marketing_consent: null, admin_graphql_api_id: 'gid://shopify/Customer/' + randomId(13) },
            line_items: [{ id: parseInt(randomId(13)), variant_id: parseInt(randomId(13)), product_id: parseInt(randomId(13)), title: 'Premium Plan', variant_title: '', sku: '', vendor: 'hookswing-store', quantity: 1, requires_shipping: false, taxable: true, gift_card: false, fulfillment_service: 'manual', grams: 0, name: 'Premium Plan', variant_inventory_management: null, properties: [], product_exists: true, fulfillable_quantity: 1, total_discount: '0.00', fulfillment_status: null, price: '89.99', admin_graphql_api_id: 'gid://shopify/LineItem/' + randomId(13), tax_lines: [], price_set: { shop_money: { amount: '89.99', currency_code: 'USD' }, presentment_money: { amount: '89.99', currency_code: 'USD' } }, total_discount_set: { shop_money: { amount: '0.00', currency_code: 'USD' }, presentment_money: { amount: '0.00', currency_code: 'USD' } } }],
          },
        },
      },
      'products/create': {
        label: 'Product Created',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'Shopify-Captain-Hook',
            'content-type': 'application/json',
            'x-shopify-topic': 'products/create',
            'x-shopify-shop-domain': 'hookswing-store.myshopify.com',
            'x-shopify-product-id': randomId(13),
            'x-shopify-webhook-id': randomId(32),
            'x-shopify-api-version': '2024-04',
          },
          source: 'shopify',
          body: {
            id: parseInt(randomId(13)),
            title: 'Webhook Tester Pro',
            body_html: '<p>Advanced webhook testing tool</p>',
            vendor: 'HookSwing',
            product_type: 'Software',
            created_at: new Date().toISOString(),
            handle: 'webhook-tester-pro',
            updated_at: new Date().toISOString(),
            published_at: new Date().toISOString(),
            template_suffix: null,
            published_scope: 'global',
            tags: 'webhook,testing,developer-tools',
            variants: [{ id: parseInt(randomId(13)), product_id: parseInt(randomId(13)), title: 'Default Title', price: '19.99', sku: '', position: 1, inventory_policy: 'deny', compare_at_price: null, fulfillment_service: 'manual', inventory_management: null, option1: 'Default Title', option2: null, option3: null, created_at: new Date().toISOString(), updated_at: new Date().toISOString(), taxable: true, barcode: null, grams: 0, image_id: null, weight: 0, weight_unit: 'kg', inventory_item_id: parseInt(randomId(13)), inventory_quantity: 0, old_inventory_quantity: 0, requires_shipping: false, admin_graphql_api_id: 'gid://shopify/ProductVariant/' + randomId(13) }],
            options: [{ id: parseInt(randomId(13)), product_id: parseInt(randomId(13)), name: 'Title', position: 1, values: ['Default Title'] }],
            images: [],
            image: null,
            admin_graphql_api_id: 'gid://shopify/Product/' + randomId(13),
          },
        },
      },
    },
  },

  twilio: {
    name: 'Twilio',
    events: {
      'incoming.sms': {
        label: 'Incoming SMS',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'TwilioProxy/1.1',
            'content-type': 'application/x-www-form-urlencoded',
            'x-twilio-signature': 'mock_signature',
            'i-twilio-idempotency-token': randomId(32),
          },
          source: 'twilio',
          body: {
            ToCountry: 'US',
            ToState: 'CA',
            SmsMessageSid: 'SM' + randomId(32),
            NumMedia: '0',
            ToCity: 'SAN FRANCISCO',
            FromZip: '94105',
            SmsSid: 'SM' + randomId(32),
            FromState: 'CA',
            SmsStatus: 'received',
            FromCity: 'SAN FRANCISCO',
            Body: 'Test message from Twilio webhook tester',
            FromCountry: 'US',
            To: '+14155551234',
            ToZip: '94105',
            NumSegments: '1',
            MessageSid: 'SM' + randomId(32),
            AccountSid: 'AC' + randomId(32),
            From: '+14155555678',
            ApiVersion: '2010-04-01',
          },
        },
      },
      'call.status': {
        label: 'Call Status Update',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'TwilioProxy/1.1',
            'content-type': 'application/x-www-form-urlencoded',
            'x-twilio-signature': 'mock_signature',
            'i-twilio-idempotency-token': randomId(32),
          },
          source: 'twilio',
          body: {
            Called: '+14155551234',
            ToState: 'CA',
            CallerCountry: 'US',
            Direction: 'inbound',
            CallerState: 'CA',
            ToZip: '94105',
            CallSid: 'CA' + randomId(32),
            To: '+14155551234',
            CallerZip: '94105',
            ToCountry: 'US',
            CalledZip: '94105',
            ApiVersion: '2010-04-01',
            CalledCity: 'SAN FRANCISCO',
            CallStatus: 'completed',
            From: '+14155555678',
            AccountSid: 'AC' + randomId(32),
            CalledCountry: 'US',
            CallerCity: 'SAN FRANCISCO',
            ToCity: 'SAN FRANCISCO',
            FromCountry: 'US',
            Caller: '+14155555678',
            FromCity: 'SAN FRANCISCO',
            CalledState: 'CA',
            FromZip: '94105',
            FromState: 'CA',
            CallDuration: '45',
          },
        },
      },
    },
  },

  slack: {
    name: 'Slack',
    events: {
      'slash_command': {
        label: 'Slash Command',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'Slackbot 1.0 (+https://api.slack.com/robots)',
            'content-type': 'application/x-www-form-urlencoded',
            'x-slack-signature': 'v0=mock_signature',
            'x-slack-request-timestamp': String(Math.floor(Date.now() / 1000)),
          },
          source: 'slack',
          body: {
            token: randomId(24),
            team_id: 'T' + randomId(8).toUpperCase(),
            team_domain: 'hookswing',
            channel_id: 'C' + randomId(8).toUpperCase(),
            channel_name: 'webhooks',
            user_id: 'U' + randomId(8).toUpperCase(),
            user_name: 'testuser',
            command: '/testwebhook',
            text: 'hello from tester',
            api_app_id: 'A' + randomId(8).toUpperCase(),
            is_enterprise_install: 'false',
            response_url: 'https://hooks.slack.com/commands/T' + randomId(8).toUpperCase() + '/' + randomId(11) + '/' + randomId(24),
            trigger_id: randomId(11) + '.' + randomId(13) + '.' + randomId(24),
          },
        },
      },
      'interactive_message': {
        label: 'Interactive Message',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'Slackbot 1.0 (+https://api.slack.com/robots)',
            'content-type': 'application/x-www-form-urlencoded',
            'x-slack-signature': 'v0=mock_signature',
            'x-slack-request-timestamp': String(Math.floor(Date.now() / 1000)),
          },
          source: 'slack',
          body: {
            type: 'block_actions',
            user: { id: 'U' + randomId(8).toUpperCase(), username: 'testuser', name: 'testuser', team_id: 'T' + randomId(8).toUpperCase() },
            api_app_id: 'A' + randomId(8).toUpperCase(),
            token: randomId(24),
            container: { type: 'message', message_ts: '1234567890.123456', channel_id: 'C' + randomId(8).toUpperCase(), is_ephemeral: false },
            trigger_id: randomId(11) + '.' + randomId(13) + '.' + randomId(24),
            team: { id: 'T' + randomId(8).toUpperCase(), domain: 'hookswing' },
            channel: { id: 'C' + randomId(8).toUpperCase(), name: 'webhooks' },
            message: { type: 'message', user: 'U' + randomId(8).toUpperCase(), ts: '1234567890.123456', text: 'Test message', blocks: [{ type: 'section', block_id: 'test-block', text: { type: 'mrkdwn', text: '*Webhook Tester*', verbatim: false } }], team: 'T' + randomId(8).toUpperCase() },
            actions: [{ action_id: 'test-action', block_id: 'test-block', text: { type: 'plain_text', text: 'Click me', emoji: true }, type: 'button', action_ts: String(Math.floor(Date.now() / 1000)) }],
            state: { values: {} },
            response_url: 'https://hooks.slack.com/actions/T' + randomId(8).toUpperCase() + '/' + randomId(11) + '/' + randomId(24),
          },
        },
      },
    },
  },

  discord: {
    name: 'Discord',
    events: {
      'interaction': {
        label: 'Interaction (Slash Command)',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'Discord-Interactions/1.0 (+https://discord.com)',
            'content-type': 'application/json',
            'x-signature-ed25519': randomHex(64),
            'x-signature-timestamp': String(Math.floor(Date.now() / 1000)),
          },
          source: 'discord',
          body: {
            id: randomId(19),
            application_id: randomId(19),
            type: 2,
            token: randomId(50),
            version: 1,
            guild_id: randomId(19),
            channel_id: randomId(19),
            member: {
              user: { id: randomId(19), username: 'testuser', avatar: null, discriminator: '1234', public_flags: 0, flags: 0, bot: false },
              roles: [],
              premium_since: null,
              permissions: '2147483647',
              pending: false,
              nick: null,
              mute: false,
              joined_at: new Date().toISOString(),
              is_pending: false,
              deaf: false,
              avatar: null,
            },
            data: { id: randomId(19), name: 'testwebhook', type: 1, options: [{ name: 'message', type: 3, value: 'hello from tester' }] },
            locale: 'en-US',
            guild_locale: 'en-US',
          },
        },
      },
    },
  },

  microsoft_teams: {
    name: 'Microsoft Teams',
    events: {
      'outgoing_webhook': {
        label: 'Outgoing Webhook',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'Microsoft Teams Infrastructure',
            'content-type': 'application/json',
            'authorization': 'Bearer ' + randomId(100),
          },
          source: 'microsoft_teams',
          body: {
            type: 'message',
            id: randomId(19),
            timestamp: new Date().toISOString(),
            serviceUrl: 'https://smba.trafficmanager.net/amer/',
            channelId: 'msteams',
            from: { id: '29:' + randomId(32), name: 'Test User', aadObjectId: randomId(36) },
            conversation: { conversationType: 'personal', tenantId: randomId(36), id: 'a:' + randomId(32) },
            recipient: { id: '28:' + randomId(32), name: 'Webhook Bot' },
            textFormat: 'plain',
            text: 'Hello bot',
            attachments: [],
            entities: [],
            channelData: { tenant: { id: randomId(36) } },
            locale: 'en-US',
          },
        },
      },
    },
  },

  sendgrid: {
    name: 'SendGrid',
    events: {
      delivered: {
        label: 'Email Delivered',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'SendGrid Event API',
            'content-type': 'application/json',
          },
          source: 'sendgrid',
          body: [
            {
              email: 'customer@example.com',
              timestamp: Math.floor(Date.now() / 1000),
              'smtp-id': '<' + randomId(32) + '@sendgrid.net>',
              event: 'delivered',
              category: ['webhook_test'],
              sg_event_id: randomId(22),
              sg_message_id: randomId(22),
              response: '250 OK',
              attempt: '1',
            },
          ],
        },
      },
      open: {
        label: 'Email Opened',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'SendGrid Event API',
            'content-type': 'application/json',
          },
          source: 'sendgrid',
          body: [
            {
              email: 'customer@example.com',
              timestamp: Math.floor(Date.now() / 1000),
              'smtp-id': '<' + randomId(32) + '@sendgrid.net>',
              event: 'open',
              category: ['webhook_test'],
              sg_event_id: randomId(22),
              sg_message_id: randomId(22),
              useragent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
              ip: '192.168.1.1',
            },
          ],
        },
      },
      bounce: {
        label: 'Email Bounced',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'SendGrid Event API',
            'content-type': 'application/json',
          },
          source: 'sendgrid',
          body: [
            {
              email: 'invalid@example.com',
              timestamp: Math.floor(Date.now() / 1000),
              'smtp-id': '<' + randomId(32) + '@sendgrid.net>',
              event: 'bounce',
              category: ['webhook_test'],
              sg_event_id: randomId(22),
              sg_message_id: randomId(22),
              reason: '550 5.1.1 The email account that you tried to reach does not exist.',
              status: '5.1.1',
              type: 'bounce',
            },
          ],
        },
      },
    },
  },

  mailgun: {
    name: 'Mailgun',
    events: {
      delivered: {
        label: 'Email Delivered',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'Mailgun/1.0',
            'content-type': 'application/json',
          },
          source: 'mailgun',
          body: {
            event: 'delivered',
            id: randomId(24),
            timestamp: Math.floor(Date.now() / 1000),
            log_level: 'info',
            envelope: { transport: 'smtp', sender: 'postmaster@mg.example.com', targeting: 'rcpt', recipient: ['customer@example.com'] },
            flags: { is_routed: false, is_authenticated: true, is_system: false, is_test_mode: false },
            delivery_status: { tls: true, mx_host: 'gmail-smtp-in.l.google.com', code: 250, description: '', session: true, certificate_verified: true, retry_seconds: 0, utf8: true, attempt_no: 1, message: '', certificate: [] },
            message: { headers: { to: 'customer@example.com', message_id: randomId(24) + '@mg.example.com', from: 'sender@example.com', subject: 'Test Email' }, attachments: [], size: 1234 },
            recipient: 'customer@example.com',
            recipient_domain: 'example.com',
            campaigns: [],
            tags: ['webhook_test'],
            'user-variables': {},
            routes: [],
            storage: { url: 'https://se.api.mailgun.net/v3/domains/mg.example.com/messages/' + randomId(24), key: randomId(24) },
          },
        },
      },
      opened: {
        label: 'Email Opened',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'Mailgun/1.0',
            'content-type': 'application/json',
          },
          source: 'mailgun',
          body: {
            event: 'opened',
            id: randomId(24),
            timestamp: Math.floor(Date.now() / 1000),
            log_level: 'info',
            envelope: { sender: 'postmaster@mg.example.com', transport: '' },
            flags: { is_routed: false, is_authenticated: false, is_system: false, is_test_mode: false },
            client_info: { client_type: 'browser client', client_os: 'Linux', device_type: 'desktop', client_name: 'Chrome', user_agent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36' },
            geolocation: { country: 'US', region: 'California', city: 'San Francisco' },
            message: { headers: { to: 'customer@example.com', message_id: randomId(24) + '@mg.example.com', from: 'sender@example.com', subject: 'Test Email' }, attachments: [], size: 1234 },
            recipient: 'customer@example.com',
            recipient_domain: 'example.com',
            campaigns: [],
            tags: ['webhook_test'],
            'user-variables': {},
          },
        },
      },
    },
  },

  zoom: {
    name: 'Zoom',
    events: {
      'meeting.started': {
        label: 'Meeting Started',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'Zoom/1.0',
            'content-type': 'application/json',
            'authorization': 'v0=' + randomHex(64),
          },
          source: 'zoom',
          body: {
            event: 'meeting.started',
            payload: {
              account_id: randomId(22),
              object: {
                uuid: randomId(22),
                id: parseInt(randomId(11)),
                host_id: randomId(22),
                topic: 'Webhook Test Meeting',
                type: 2,
                start_time: new Date().toISOString(),
                duration: 60,
                timezone: 'America/Los_Angeles',
                created_at: new Date().toISOString(),
                join_url: 'https://zoom.us/j/' + randomId(11),
                password: randomId(6),
              },
            },
            event_ts: Date.now(),
          },
        },
      },
      'participant.joined': {
        label: 'Participant Joined',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'Zoom/1.0',
            'content-type': 'application/json',
            'authorization': 'v0=' + randomHex(64),
          },
          source: 'zoom',
          body: {
            event: 'meeting.participant_joined',
            payload: {
              account_id: randomId(22),
              object: {
                uuid: randomId(22),
                id: parseInt(randomId(11)),
                host_id: randomId(22),
                topic: 'Webhook Test Meeting',
                type: 2,
                start_time: new Date().toISOString(),
                duration: 60,
                timezone: 'America/Los_Angeles',
                participant: { user_id: randomId(22), user_name: 'Test User', id: randomId(22), join_time: new Date().toISOString(), email: 'test@example.com', participant_uuid: randomId(22) },
              },
            },
            event_ts: Date.now(),
          },
        },
      },
      'recording.completed': {
        label: 'Recording Completed',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'Zoom/1.0',
            'content-type': 'application/json',
            'authorization': 'v0=' + randomHex(64),
          },
          source: 'zoom',
          body: {
            event: 'recording.completed',
            payload: {
              account_id: randomId(22),
              object: {
                uuid: randomId(22),
                id: parseInt(randomId(11)),
                account_id: randomId(22),
                host_id: randomId(22),
                topic: 'Webhook Test Meeting',
                type: 2,
                start_time: new Date().toISOString(),
                timezone: 'America/Los_Angeles',
                duration: 60,
                total_size: 12345678,
                recording_count: 2,
                recording_files: [
                  { id: randomId(22), meeting_id: randomId(22), recording_start: new Date().toISOString(), recording_end: new Date(Date.now() + 3600000).toISOString(), file_type: 'MP4', file_extension: 'mp4', file_size: 9876543, play_url: 'https://zoom.us/rec/play/' + randomId(22), download_url: 'https://zoom.us/rec/download/' + randomId(22), status: 'completed', recording_type: 'shared_screen_with_speaker_view' },
                  { id: randomId(22), meeting_id: randomId(22), recording_start: new Date().toISOString(), recording_end: new Date(Date.now() + 3600000).toISOString(), file_type: 'M4A', file_extension: 'm4a', file_size: 2469135, play_url: 'https://zoom.us/rec/play/' + randomId(22), download_url: 'https://zoom.us/rec/download/' + randomId(22), status: 'completed', recording_type: 'audio_only' },
                ],
              },
            },
            event_ts: Date.now(),
          },
        },
      },
    },
  },

  calendly: {
    name: 'Calendly',
    events: {
      'invitee.created': {
        label: 'Invitee Created',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'Calendly/1.0',
            'content-type': 'application/json',
            'calendly-webhook-signature': 'v0=' + randomHex(64),
          },
          source: 'calendly',
          body: {
            event: 'invitee.created',
            payload: {
              event_type: { uuid: randomId(32), kind: 'EventType', slug: '30min', name: '30 Minute Meeting', duration: 30, owner: { type: 'User', uuid: randomId(32) } },
              event: { uuid: randomId(32), kind: 'Event', start_time: new Date(Date.now() + 86400000).toISOString(), end_time: new Date(Date.now() + 86400000 + 1800000).toISOString() },
              invitee: { uuid: randomId(32), first_name: 'Test', last_name: 'Customer', name: 'Test Customer', email: 'customer@example.com', timezone: 'America/Los_Angeles', created_at: new Date().toISOString(), updated_at: new Date().toISOString(), tracking: {} },
              questions_and_answers: [],
              questions_and_responses: {},
              utm: {},
              text_reminder_number: null,
              timezone: 'America/Los_Angeles',
              old_event: null,
              old_invitee: null,
              new_event: null,
              new_invitee: null,
              cancel_url: 'https://calendly.com/cancellations/' + randomId(32),
              reschedule_url: 'https://calendly.com/reschedulings/' + randomId(32),
              created_at: new Date().toISOString(),
              updated_at: new Date().toISOString(),
            },
            created_at: new Date().toISOString(),
            created_by: 'https://api.calendly.com/users/' + randomId(32),
            updated_at: new Date().toISOString(),
          },
        },
      },
      'invitee.canceled': {
        label: 'Invitee Canceled',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'Calendly/1.0',
            'content-type': 'application/json',
            'calendly-webhook-signature': 'v0=' + randomHex(64),
          },
          source: 'calendly',
          body: {
            event: 'invitee.canceled',
            payload: {
              event_type: { uuid: randomId(32), kind: 'EventType', slug: '30min', name: '30 Minute Meeting', duration: 30, owner: { type: 'User', uuid: randomId(32) } },
              event: { uuid: randomId(32), kind: 'Event', start_time: new Date(Date.now() + 86400000).toISOString(), end_time: new Date(Date.now() + 86400000 + 1800000).toISOString() },
              invitee: { uuid: randomId(32), first_name: 'Test', last_name: 'Customer', name: 'Test Customer', email: 'customer@example.com', timezone: 'America/Los_Angeles', created_at: new Date().toISOString(), updated_at: new Date().toISOString(), tracking: {}, cancel_reason: 'Schedule changed', canceled_by: 'Test Customer' },
              questions_and_answers: [],
              questions_and_responses: {},
              utm: {},
              text_reminder_number: null,
              timezone: 'America/Los_Angeles',
              old_event: null,
              old_invitee: null,
              new_event: null,
              new_invitee: null,
              cancel_url: 'https://calendly.com/cancellations/' + randomId(32),
              reschedule_url: 'https://calendly.com/reschedulings/' + randomId(32),
              created_at: new Date().toISOString(),
              updated_at: new Date().toISOString(),
            },
            created_at: new Date().toISOString(),
            created_by: 'https://api.calendly.com/users/' + randomId(32),
            updated_at: new Date().toISOString(),
          },
        },
      },
    },
  },

  typeform: {
    name: 'Typeform',
    events: {
      'form_response': {
        label: 'Form Response',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'Typeform/1.0',
            'content-type': 'application/json',
          },
          source: 'typeform',
          body: {
            event_id: randomId(17),
            event_type: 'form_response',
            form_response: {
              form_id: randomId(6).toUpperCase(),
              token: randomId(32),
              submitted_at: new Date().toISOString(),
              landed_at: new Date(Date.now() - 120000).toISOString(),
              calculated: { score: 0 },
              variables: [],
              definition: {
                id: randomId(6).toUpperCase(),
                title: 'Webhook Test Form',
                fields: [
                  { id: randomId(8).toUpperCase(), title: 'What is your name?', type: 'short_text', ref: 'name', properties: {} },
                  { id: randomId(8).toUpperCase(), title: 'What is your email?', type: 'email', ref: 'email', properties: {} },
                  { id: randomId(8).toUpperCase(), title: 'How satisfied are you?', type: 'opinion_scale', ref: 'satisfaction', properties: { steps: 10, start_at_one: true } },
                ],
              },
              answers: [
                { type: 'text', text: 'Test Customer', field: { id: randomId(8).toUpperCase(), type: 'short_text', ref: 'name' } },
                { type: 'email', email: 'customer@example.com', field: { id: randomId(8).toUpperCase(), type: 'email', ref: 'email' } },
                { type: 'number', number: 8, field: { id: randomId(8).toUpperCase(), type: 'opinion_scale', ref: 'satisfaction' } },
              ],
              ending: { id: 'default', ref: 'default' },
            },
          },
        },
      },
    },
  },

  google: {
    name: 'Google',
    events: {
      'pubsub.push': {
        label: 'Pub/Sub Push',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'APIs-Google; (+https://developers.google.com/webmasters/APIs-Google.html)',
            'content-type': 'application/json',
          },
          source: 'google',
          body: {
            message: {
              attributes: { key: 'value' },
              data: Buffer.from(JSON.stringify({ event: 'test', timestamp: Date.now() })).toString('base64'),
              messageId: randomId(19),
              message_id: randomId(19),
              publishTime: new Date().toISOString(),
              publish_time: new Date().toISOString(),
            },
            subscription: 'projects/hookswing/subscriptions/webhook-sub',
          },
        },
      },
      'calendar.event': {
        label: 'Calendar Event Update',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'Google-Calendar-Importer',
            'content-type': 'application/json',
          },
          source: 'google',
          body: {
            kind: 'calendar#event',
            etag: '"' + randomId(16) + '"',
            id: randomId(26).toLowerCase(),
            status: 'confirmed',
            htmlLink: 'https://www.google.com/calendar/event?eid=' + randomId(26).toLowerCase(),
            created: new Date().toISOString(),
            updated: new Date().toISOString(),
            summary: 'Webhook Test Meeting',
            description: 'Testing webhooks with Google Calendar',
            location: 'San Francisco, CA',
            creator: { email: 'organizer@example.com', self: true },
            organizer: { email: 'organizer@example.com', self: true },
            start: { dateTime: new Date(Date.now() + 3600000).toISOString(), timeZone: 'America/Los_Angeles' },
            end: { dateTime: new Date(Date.now() + 7200000).toISOString(), timeZone: 'America/Los_Angeles' },
            iCalUID: randomId(26).toLowerCase() + '@google.com',
            sequence: 0,
            attendees: [{ email: 'attendee@example.com', responseStatus: 'accepted' }],
            reminders: { useDefault: true },
          },
        },
      },
    },
  },

  square: {
    name: 'Square',
    events: {
      'payment.created': {
        label: 'Payment Created',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'Square/1.0',
            'content-type': 'application/json',
            'x-square-signature': randomHex(64),
          },
          source: 'square',
          body: {
            merchant_id: randomId(16),
            type: 'payment.created',
            event_id: randomId(32),
            created_at: new Date().toISOString(),
            data: {
              type: 'payment',
              id: randomId(32),
              object: {
                payment: {
                  id: randomId(32),
                  created_at: new Date().toISOString(),
                  updated_at: new Date().toISOString(),
                  amount_money: { amount: 1999, currency: 'USD' },
                  app_fee_money: { amount: 0, currency: 'USD' },
                  total_money: { amount: 1999, currency: 'USD' },
                  status: 'COMPLETED',
                  delay_duration: 'PT168H',
                  delay_action: 'CANCEL',
                  delayed_until: new Date(Date.now() + 168 * 3600000).toISOString(),
                  source_type: 'CARD',
                  card_details: {
                    status: 'CAPTURED',
                    card: { card_brand: 'VISA', last_4: '4242', exp_month: 12, exp_year: 2025, fingerprint: randomId(48), card_type: 'CREDIT', prepaid_type: 'NOT_PREPAID', bin: '424242' },
                    entry_method: 'KEYED',
                    cvv_status: 'CVV_ACCEPTED',
                    avs_status: 'AVS_ACCEPTED',
                    auth_result_code: 'mock',
                    statement_description: 'HOOKSWING',
                  },
                  location_id: randomId(16),
                  order_id: randomId(32),
                  risk_evaluation: { created_at: new Date().toISOString(), risk_level: 'NORMAL' },
                  buyer_email_address: 'customer@example.com',
                  billing_address: { address_line_1: '123 Market St', locality: 'San Francisco', administrative_district_level_1: 'CA', postal_code: '94105', country: 'US' },
                  note: 'Test payment from webhook tester',
                  approved_money: { amount: 1999, currency: 'USD' },
                  receipt_number: randomId(4),
                  receipt_url: 'https://squareup.com/receipt/preview/' + randomId(32),
                  version_token: randomId(32),
                },
              },
            },
          },
        },
      },
      'order.created': {
        label: 'Order Created',
        payload: {
          method: 'POST',
          headers: {
            'user-agent': 'Square/1.0',
            'content-type': 'application/json',
            'x-square-signature': randomHex(64),
          },
          source: 'square',
          body: {
            merchant_id: randomId(16),
            type: 'order.created',
            event_id: randomId(32),
            created_at: new Date().toISOString(),
            data: {
              type: 'order',
              id: randomId(32),
              object: {
                order: {
                  id: randomId(32),
                  location_id: randomId(16),
                  reference_id: randomId(8).toUpperCase(),
                  source: { name: 'Webhook Tester' },
                  customer_id: randomId(32),
                  line_items: [
                    { uid: randomId(8).toUpperCase(), quantity: '1', name: 'Premium Plan', base_price_money: { amount: 1999, currency: 'USD' }, gross_sales_money: { amount: 1999, currency: 'USD' }, total_money: { amount: 1999, currency: 'USD' }, total_tax_money: { amount: 0, currency: 'USD' }, total_discount_money: { amount: 0, currency: 'USD' } },
                  ],
                  taxes: [],
                  discounts: [],
                  metadata: { note: 'Test order' },
                  created_at: new Date().toISOString(),
                  updated_at: new Date().toISOString(),
                  state: 'OPEN',
                  version: 1,
                  total_money: { amount: 1999, currency: 'USD' },
                  total_tax_money: { amount: 0, currency: 'USD' },
                  total_discount_money: { amount: 0, currency: 'USD' },
                  total_tip_money: { amount: 0, currency: 'USD' },
                  fulfillments: [],
                  net_amounts: { total_money: { amount: 1999, currency: 'USD' }, tax_money: { amount: 0, currency: 'USD' }, discount_money: { amount: 0, currency: 'USD' }, tip_money: { amount: 0, currency: 'USD' }, service_charge_money: { amount: 0, currency: 'USD' } },
                  pricing_options: { auto_apply_discounts: false, auto_apply_taxes: false },
                },
              },
            },
          },
        },
      },
    },
  },

  generic: {
    name: 'Generic',
    events: {
      'json.payload': {
        label: 'JSON Payload',
        payload: {
          method: 'POST',
          headers: {
            'content-type': 'application/json',
            'x-webhook-source': 'generic-tester',
            'x-request-id': randomId(32),
          },
          source: 'generic',
          body: {
            event: 'test.event',
            timestamp: new Date().toISOString(),
            data: {
              id: randomId(24),
              type: 'test',
              message: 'This is a generic test payload',
              metadata: { source: 'hookswing-tester', version: '1.0' },
            },
          },
        },
      },
      'form.payload': {
        label: 'Form URL-Encoded Payload',
        payload: {
          method: 'POST',
          headers: {
            'content-type': 'application/x-www-form-urlencoded',
            'x-webhook-source': 'generic-tester',
            'x-request-id': randomId(32),
          },
          source: 'generic',
          body: {
            event: 'test.event',
            timestamp: new Date().toISOString(),
            id: randomId(24),
            message: 'This is a generic form-encoded test payload',
            status: 'active',
          },
        },
      },
    },
  },
};

// ── Helpers ──
function randomId(len: number): string {
  const chars = 'abcdefghijklmnopqrstuvwxyz0123456789';
  let result = '';
  for (let i = 0; i < len; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}

function randomHex(len: number): string {
  let result = '';
  for (let i = 0; i < len; i++) {
    result += Math.floor(Math.random() * 16).toString(16);
  }
  return result;
}
